require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HavesController do

  # This should return the minimal set of attributes required to create a valid
  # Have. As you add validations to Have, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all haves as @haves" do
      have = Have.create! valid_attributes
      get :index
      assigns(:haves).should eq([have])
    end
  end

  describe "GET show" do
    it "assigns the requested have as @have" do
      have = Have.create! valid_attributes
      get :show, :id => have.id.to_s
      assigns(:have).should eq(have)
    end
  end

  describe "GET new" do
    it "assigns a new have as @have" do
      get :new
      assigns(:have).should be_a_new(Have)
    end
  end

  describe "GET edit" do
    it "assigns the requested have as @have" do
      have = Have.create! valid_attributes
      get :edit, :id => have.id.to_s
      assigns(:have).should eq(have)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Have" do
        expect {
          post :create, :have => valid_attributes
        }.to change(Have, :count).by(1)
      end

      it "assigns a newly created have as @have" do
        post :create, :have => valid_attributes
        assigns(:have).should be_a(Have)
        assigns(:have).should be_persisted
      end

      it "redirects to the created have" do
        post :create, :have => valid_attributes
        response.should redirect_to(Have.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved have as @have" do
        # Trigger the behavior that occurs when invalid params are submitted
        Have.any_instance.stub(:save).and_return(false)
        post :create, :have => {}
        assigns(:have).should be_a_new(Have)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Have.any_instance.stub(:save).and_return(false)
        post :create, :have => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested have" do
        have = Have.create! valid_attributes
        # Assuming there are no other haves in the database, this
        # specifies that the Have created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Have.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => have.id, :have => {'these' => 'params'}
      end

      it "assigns the requested have as @have" do
        have = Have.create! valid_attributes
        put :update, :id => have.id, :have => valid_attributes
        assigns(:have).should eq(have)
      end

      it "redirects to the have" do
        have = Have.create! valid_attributes
        put :update, :id => have.id, :have => valid_attributes
        response.should redirect_to(have)
      end
    end

    describe "with invalid params" do
      it "assigns the have as @have" do
        have = Have.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Have.any_instance.stub(:save).and_return(false)
        put :update, :id => have.id.to_s, :have => {}
        assigns(:have).should eq(have)
      end

      it "re-renders the 'edit' template" do
        have = Have.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Have.any_instance.stub(:save).and_return(false)
        put :update, :id => have.id.to_s, :have => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested have" do
      have = Have.create! valid_attributes
      expect {
        delete :destroy, :id => have.id.to_s
      }.to change(Have, :count).by(-1)
    end

    it "redirects to the haves list" do
      have = Have.create! valid_attributes
      delete :destroy, :id => have.id.to_s
      response.should redirect_to(haves_url)
    end
  end

end
